theme: jekyll-theme-cayman
#Glossaire
					Glossaire: 

Additifs = “Nom générique de substances qui, additionnées à certains produits, leur confèrent des propriétés spéciales ou améliorent leurs propriétés.” (Larousse)

Association de Consommateurs = “association reconnue officiellement par les pouvoirs publics comme représentative des intérêts des consommateurs.” (Institut National de la Consommation)

Equilibre Alimentaire = “contribuer à assurer un état de santé optimum des individus et des populations.”(Fonds Français pour l’Alimentation et la Santé)

Industrie alimentaire ou agroalimentaire (AII) = “est l'ensemble des activités industrielles qui transforment des matières premières issues de l’agriculture, de l'élevage ou de la pêche en produits alimentaires destinés essentiellement à la consommation humaine. Ainsi, l’industrie alimentaire ne comprend pas l’agriculture qui élève les produits vivants, cultive les plantes et fruits, et les fournit à l’industrie agroalimentaire.” (Pôle Emploi)

Matrice d’un aliment = “structure physique qui influence le degré de mastication, la biodisponibilité, l’index glycémique, l’anabolisme protéique, la satiété…” (Actalia.eu)

Produits ultra-transformés = “L’aliment d’origine a subi d’intenses transformations physiques, chimiques ou biologiques par des procédés industriels (par exemple : fractionnement d’un aliment en de multiple composants – craking - prétraitement par friture, chauffage à très haute température…). Des additifs et/ou ingrédients (maltodetxrine, huiles hydrogénées, amidon modifié…) réservés à l’usage industriel et qui ne sont pas utilisés en cuisine à la maison, sont souvent ajoutés pour arriver au produit final que l’on retrouve dans nos rayons.” (site gouvernemental MangerBouger.fr)

Transition alimentaire = “désigne dans son acception globale le processus par lequel une société modifie sa manière de produire et de consommer des aliments. Au sens premier, le modèle de la transition alimentaire est un modèle d'évolution développé dans les années 2000. Il reprend le modèle de « transition nutritionnelle » introduit dans les années 1990 par des nutritionnistes (Popkin, 1993)..” (Géoconfluence)

